### ISSUE TITLE
Открывающая фигурная скобка не должна переноситься на новую строку

### ISSUE THREAD

**Issue by Comradevergreen** [OMV0102/AndroidApp1#2]
https://github.com/OMV0102/AndroidApp1/blob/c9689a81c4a57f0f2dbf0c587b2ce62fd9143d7f/src/main/kotlin/Main.kt#L8

Чтобы студия сама отформатировала код можно нажать Ctrl+Alt+L

**Comment by OMV0102** [comment]
но ведь... это всего лишь стиль кода, я специально в настройках студии изменил под себя положение скобок и переносов строк, так как привык к такому

**Comment by Comradevergreen** [comment]
Вообще да, это скорее небольшое замечание. Чаще всего в андроид проектах разработчики придерживаются определенного code style
